# Generated by Django 5.2.7 on 2026-02-04 00:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(help_text='e.g., BIO101, CHM201', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Category',
                'verbose_name_plural': 'Exam Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Exam instructions for students', null=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration in minutes (5-480)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('total_questions', models.IntegerField(help_text='Total number of questions in the exam', validators=[django.core.validators.MinValueValidator(1)])),
                ('passing_score', models.IntegerField(default=50, help_text='Minimum percentage to pass', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('show_answers', models.BooleanField(default=False, help_text='Show correct answers after exam submission')),
                ('show_score', models.BooleanField(default=True, help_text='Show score after exam submission')),
                ('shuffle_questions', models.BooleanField(default=True, help_text='Randomize question order for each student')),
                ('shuffle_options', models.BooleanField(default=True, help_text='Randomize answer options for each question')),
                ('allow_review', models.BooleanField(default=True, help_text='Allow students to review answered questions')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField(help_text='When exam becomes available')),
                ('end_date', models.DateTimeField(help_text='When exam closes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exams.examcategory')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple', 'Multiple Choice'), ('true_false', 'True/False'), ('short', 'Short Answer')], default='multiple', max_length=20)),
                ('marks', models.IntegerField(default=1, help_text='Points for this question', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=0, help_text='Order of question in exam')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after exam (if enabled)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['exam', 'order'],
                'unique_together': {('exam', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False, help_text='Mark this as the correct answer')),
                ('order', models.IntegerField(default=0, help_text='Display order of answer option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question')),
            ],
            options={
                'verbose_name': 'Answer Option',
                'verbose_name_plural': 'Answer Options',
                'ordering': ['question', 'order'],
                'unique_together': {('question', 'order')},
            },
        ),
    ]
