# Generated by Django 5.2.7 on 2026-02-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_correct_answer_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diagram_image',
            field=models.ImageField(blank=True, help_text='Diagram for physics and other science questions', null=True, upload_to='question_diagrams/'),
        ),
        migrations.AddField(
            model_name='question',
            name='equation_type',
            field=models.CharField(blank=True, choices=[('algebraic', 'Algebraic'), ('chemical', 'Chemical'), ('physics', 'Physics'), ('statistical', 'Statistical')], help_text='Type of equation for math/science questions', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='latex_content',
            field=models.TextField(blank=True, help_text='LaTeX content for math and science questions', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('short', 'Short Answer'), ('math', 'Mathematical'), ('chemistry', 'Chemistry Equation'), ('physics', 'Physics Diagram')], default='multiple', max_length=20),
        ),
    ]
