# Generated by Django 6.0.1 on 2026-02-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_diagram_image_question_equation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('short', 'Short Answer'), ('math', 'Mathematical'), ('chemistry', 'Chemistry Equation'), ('physics', 'Physics Diagram'), ('biology', 'Biology Diagram')], default='multiple', max_length=20),
        ),
    ]
