# Generated by Django 6.0.1 on 2026-02-14 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_question_question_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comprehension_group',
            field=models.CharField(blank=True, help_text='Group identifier for questions sharing the same passage', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='comprehension_passage',
            field=models.TextField(blank=True, help_text='Shared passage for comprehension questions (will be shown for all questions in the same group)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('short', 'Short Answer'), ('math', 'Mathematical'), ('chemistry', 'Chemistry Equation'), ('physics', 'Physics Diagram'), ('biology', 'Biology Diagram'), ('comprehension', 'Comprehension')], default='multiple', max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description of the image', max_length=200)),
                ('image', models.ImageField(help_text='Image file that can be referenced by multiple questions', upload_to='shared_question_images/')),
                ('caption', models.TextField(blank=True, help_text='Caption or description for the image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Image',
                'verbose_name_plural': 'Question Images',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='shared_image',
            field=models.ForeignKey(blank=True, help_text='Reference to a shared image that can be used by multiple questions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_questions', to='exams.questionimage'),
        ),
    ]
