# Generated by Django 5.2.12 on 2026-08-10 10:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_question_comprehension_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions_per_paper',
            field=models.IntegerField(blank=True, help_text='Number of questions each batch paper randomly draws from the question bank. Leave blank to use all questions.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='ExamBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Batch 1', max_length=100)),
                ('start_time', models.DateTimeField(help_text="When this batch's window opens")),
                ('end_time', models.DateTimeField(help_text="When this batch's window closes")),
                ('order', models.IntegerField(default=0, help_text='Display order of the batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='exams.exam')),
                ('questions', models.ManyToManyField(blank=True, help_text='The paper (randomly drawn questions) for this batch', related_name='batch_papers', to='exams.question')),
                ('students', models.ManyToManyField(blank=True, help_text='Students assigned to this batch', related_name='exam_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Batch',
                'verbose_name_plural': 'Exam Batches',
                'ordering': ['exam', 'order'],
            },
        ),
    ]
