# Generated by Django 5.2.12 on 2026-08-10 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_questions_per_paper_exambatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exambatch',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='exambatch',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='exambatch',
            name='students',
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions_per_paper',
            field=models.IntegerField(blank=True, help_text="Number of questions randomly drawn from the question bank for each student's paper. Leave blank to use all questions.", null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
