# Generated by Django 5.2.12 on 2026-08-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_exambatch_exam_remove_exambatch_questions_and_more'),
        ('results', '0006_remove_examattempt_batch_examattempt_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamBatch',
        ),
    ]
