# Generated by Django 5.2.7 on 2026-02-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('matriculated', 'Matriculated Student'), ('100level', '100 Level Student'), ('intending', 'Intending Student')], default='matriculated', max_length=20),
        ),
    ]
