# Generated by Django 5.2.7 on 2026-02-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_plain_password',
            field=models.CharField(blank=True, help_text='Temporary storage of plain password for credential export', max_length=255, null=True),
        ),
    ]
