# Generated by Django 6.0.1 on 2026-02-04 22:18

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_temporary_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jamb_number',
            field=models.CharField(blank=True, help_text='Format: 202330951815BA (12-13 digits + 2 uppercase letters)', max_length=15, null=True, unique=True, validators=[users.models.validate_jamb_number]),
        ),
    ]
