# Generated by Django 5.2.12 on 2026-08-08

from django.db import migrations, models


def clear_forced_password_change(apps, schema_editor):
    """Passwords distributed to students are now permanent; stop forcing
    everyone (including already-created accounts) to change theirs on login."""
    User = apps.get_model('users', 'User')
    User.objects.update(is_first_login=False, temporary_password=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='temporary_password',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            clear_forced_password_change,
            migrations.RunPython.noop,
        ),
    ]
